name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Ensure CNAME
        run: echo "www.deltrivx.com" > docs/CNAME

      - name: Commit CNAME
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/CNAME
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update CNAME [skip ci]"
            git push
          fi
